application: asperadashboard
version: bq
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /static/css
  static_dir: static/css

- url: .*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: webob
  version: "1.1.1"
